# 1.1.0.0
#
# created: 02 Dec 2021
# updated: 18 Mar 2022
#
# https://github.com/actions/setup-dotnet

name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: | 
          3.1.x
          3.5.x
          4.6.x
          4.7.x
          5.0.x
          6.0.x
        include-prerelease: true
    - name: Build MoarKerbals
      run: dotnet build  ./source/MoarKerbals.csproj
      # - run: dotnet build <my project>
